"""
STAT 418 · Chapter 6.10 — Chapter Summary
Script 01: an end-to-end workflow combining the chapter's techniques.

A minimal but complete pipeline:
  preprocess (6.3) -> embed (6.2) -> annotate with self-consistency (6.4 + 6.6)
  -> evaluate with Cohen's kappa (6.8) -> disclose (6.9).

Uses llama3.2:latest throughout: the embed step needs an embedding-capable model,
and gemma3 has no embedding endpoint. Calls are spaced by RATE_LIMIT_DELAY to stay
under the ~20 requests/minute limit (25 annotation calls, so allow ~90 seconds).

Prereqs / run: see ../ch6_1_foundations/01_first_chat.py. (scikit-learn.)
"""
from __future__ import annotations

import os
import re
import sys
import time
from collections import Counter

from sklearn.metrics import cohen_kappa_score

from genai_studio import GenAIStudio

MODEL = "llama3.2:latest"
RATE_LIMIT_DELAY = 3.5  # seconds between calls -> ~17 req/min, under the ~20/min limit

PROMPT = ("Classify as positive, negative, or neutral. Respond with ONLY one word.\n"
          "Text: {text}\nLabel:")


def clean(text: str) -> str:
    """Preprocess (Section 6.3): strip HTML and collapse whitespace."""
    text = re.sub(r"<[^>]+>", "", text)
    return re.sub(r"\s+", " ", text).strip()


def make_client() -> GenAIStudio:
    if not os.environ.get("GENAI_STUDIO_API_KEY"):
        sys.exit("GENAI_STUDIO_API_KEY is not set - see ../ch6_1_foundations/01_first_chat.py.")
    ai = GenAIStudio()
    ai.select_model(MODEL)
    return ai


def main() -> None:
    ai = make_client()

    reviews = ["Great product!", "Terrible quality.", "It works fine.",
               "Best purchase ever!", "Waste of money."]
    cleaned = [clean(r) for r in reviews]

    # 1-2. Preprocess + embed (Sections 6.3, 6.2)
    embeddings = ai.embed(cleaned)
    print(f"1-2. Preprocess + embed: {len(embeddings)} reviews ({len(embeddings[0])} dims)")

    # 3. Annotate with 5-run self-consistency (Sections 6.4 + 6.6)
    print("\n3. Annotate with self-consistency (5 runs each):")
    annotations, first = [], True
    for text in cleaned:
        runs = []
        for _ in range(5):
            if not first:
                time.sleep(RATE_LIMIT_DELAY)
            first = False
            try:
                runs.append(ai.chat(PROMPT.format(text=text)).strip().lower())
            except Exception:
                runs.append("unparseable")
        majority, count = Counter(runs).most_common(1)[0]
        annotations.append(majority)
        print(f"   [{majority:>8}] ({count / 5:.0%}) {text}")

    # 4. Evaluate (Section 6.8)
    ground_truth = ["positive", "negative", "neutral", "positive", "negative"]
    kappa = cohen_kappa_score(ground_truth, annotations)
    print(f"\n4. Evaluate: Cohen's kappa vs. ground truth = {kappa:.3f}")

    # 5. Disclose (Section 6.8)
    print(f"\n5. Disclosure: labels generated by {MODEL} via Purdue GenAI Studio with "
          f"5-run\n   self-consistency; agreement with ground truth kappa = {kappa:.3f}.")


if __name__ == "__main__":
    main()
