name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Ruby environment
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
          bundler-cache: true

      # Step 3: Install Mermaid CLI (if required)
      - name: Install Mermaid CLI
        run: npm install -g mermaid.cli

      # Step 4: Install dependencies with Bundler
      - name: Install Ruby dependencies
        run: bundle install

      # Step 5: Setup deployment options
      - name: Setup deploy options
        id: setup
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then # Pull request
            echo "Detected pull request, skipping push."
            echo "NO_PUSH=--no-push" >> $GITHUB_ENV
          fi
          SRC_BRANCH=${GITHUB_REF#refs/heads/}
          echo "SRC_BRANCH=${SRC_BRANCH}" >> $GITHUB_ENV
          echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_ENV

      # Step 6: Deploy the website
      - name: Deploy website
        run: |
          yes | bash bin/deploy --verbose ${{ env.NO_PUSH }} \
                                --src ${{ env.SRC_BRANCH }} \
                                --deploy ${{ env.DEPLOY_BRANCH }}
